# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='users',
        ),
    ]
